version: "2"

networks:
  proxy-to-api:
    driver: bridge
  proxy-to-socket:
    driver: bridge

services:
  proxy:
    image: heojun990322/proxy
    ports:
      - 80:80
    networks:
      - proxy-to-api
      - proxy-to-socket
  api:
    image: heojun990322/api
    ports:
      - 8000:8000
    networks:
      - proxy-to-api
  socket:
    image: heojun990322/socket
    ports:
      - 5000:5000
    networks:
      - proxy-to-socket
